Feat show board
klkelley/tictactoe-java pull request #3
Opened 2018-01-08 22:41 UTC by klkelley

2018-01-08 23:52 UTC, aaronlahey commented
Side note: It looks like you need to set your git name and email address for this new repo. You can set those globally or you can do it per-repo.

2018-01-09 01:31 UTC, aaronlahey requested changes
One thing I'm finding interesting is 1-to-1 correspondence of classes to test classes. Did you truly test-drive this functionality or did you write tests after the fact?

2018-01-09 01:31 UTC, aaronlahey commented on src/main/java/me/karakelley/tictactoe/BoardInterface.java
> +public class BoardInterface {
`BoardInterface` is kind of a strange name... especially because Java has `interface`s and you have a concrete `class` with `Interface` in the name. Maybe do some Googling (and a blog) on the presenter pattern.

2018-01-09 01:31 UTC, aaronlahey commented on src/main/java/me/karakelley/tictactoe/Main.java
> +      userInterface.displayBoard();
I don't love that more and more methods are gathering here. This is effectively untested code. Ideally, the `main` function would set up your web of objects, and then simply start your program.

2018-01-09 01:31 UTC, aaronlahey commented on src/test/java/me/karakelley/tictactoe/BoardInterfaceTest.java
> +    assertEquals("   |   |   \n" +
I would refactor this so the board lines align and the test reads more clearly. You could do this a number of ways...

1. Just realign the strings manually (which will probably be reverted if you clean up code in IntelliJ
1. Use a `StringBuilder`
1. Create a helper method which takes and concatenates a variable number of strings (it would probably use a StringBuilder internally).

2018-01-09 01:31 UTC, aaronlahey commented on src/test/java/me/karakelley/tictactoe/UITest.java
> +    public void testDisplayBoard() {
This looks like a duplicate test to the one above. Is this (or the other one) necessary?

2018-01-09 03:58 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/UI.java
>  public class UI {
What is the responsibility of the UI class? I would expect it to only know how to display messages to and get input from user. Here it also knows about the Board class. Maybe when you move the logic from the Main class in some kind of Runner, that will be the one that coordinates what the UI displays to the user, be it a welcome message or a formatted board

2018-01-09 22:10 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/BoardPresenter.java
> +  private ArrayList<String> makeSpaces() {
This is fine for now because the presenter is just displaying a hard-coded blank board, but once the state of the board starts to change with the placement of markers, you will just feed the current state of the board to the presenter, whose job is to display the current state in some pretty format. At that point this method will probably not belong here

2018-01-09 22:10 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/IO.java
> +    display(message);
I would argue that `getInput` should only do what it says, get the input. Here it also displays a message.

2018-01-09 22:10 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/IO.java
> +public class IO {
I like the introduction of the IO class. It's more descriptive of what it does and has clear responsibilities. You might even say it has 2, to read and to write and further introduce a Reader and Writer object. You don't need to do that. I'm just giving you food for thought

2018-01-09 22:10 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/UserInterface.java
> +  public void greetUser() {
this doesn't seem to be tested

2018-01-09 22:10 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/UserInterface.java
> +  public UserInterface(IO io, BoardPresenter board) {
BoardPresenter instance is named `board`. It's a little misleading. I would name it `boardPresenter`.

2018-01-10 17:40 UTC, merged