Feat play one space
klkelley/tictactoe-java pull request #4
Opened 2018-01-11 15:57 UTC by klkelley

2018-01-11 23:28 UTC, andarcabrera requested changes

2018-01-11 23:28 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/Main.java
> +    BoardState boardState = new BoardState(new String[]{"-", "-", "-", "-", "-", "-", "-", "-", "-"});
you should be able to just ask for a board initialState() from the BoardState class, and not have to feed details of the board here. That's too much knowledge for Main

2018-01-11 23:28 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/Main.java
> +    BoardPresenter boardPresenter = new BoardPresenter(boardState);
I don't see why the boardPresenter needs to be constructed with a boardState. Can you just give it the boardState when you need the presenter to prepare it for display e.g. `boardPresenter.prettify(boardState)`

2018-01-11 23:28 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/NumberValidator.java
> +class NumberValidator implements Validator {
Nice use of interface here

2018-01-11 23:28 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/NumberValidator.java
> +    return number > 0 && number < 10;
I cannot select spot 0 on the board :(

2018-01-11 23:28 UTC, andarcabrera commented on src/main/java/me/karakelley/tictactoe/UserInterface.java
>      displayBoard();
This `greetUser` is doing a lot. The name suggests to me it greets the user, ("Welcome to TTT"). But here it also listens for user input and displays the board. Those look like they should be separate methods, and the game can coordinate the order of operations

2018-01-11 23:28 UTC, andarcabrera commented on src/test/java/me/karakelley/tictactoe/BoardPresenterTest.java
> +  private String testBoardBuilder(String[] grid) {
It's hard to tell what going on in here unless you read all the code. And even then I can't really tell what it's supposed to look like. For the presenter test, I think it would help if it looks like an actual board. In fact in general, especially when you get to winning/tie game logic, having your test grids look like actual TTT grids makes it easier to review

2018-01-12 17:50 UTC, aaronlahey approved these changes
I have feedback, but I'd rather this get merged for the demo. Let's schedule a few minutes to go over it this afternoon.

2018-01-12 17:58 UTC, merged